---
- hosts: localhost
  roles:
  - prereqs
  - ec2-vpc
  - ansible-roles/ec2-create-group
  - ec2-instance

- hosts: localhost
  roles:
  - update-inventory
  tags: inventoryupdate

- hosts: tag_Name_ad_domain_controller
  roles:
  - addc
