---

# Windows Server 2016: ami-3633b149

- block:
  - name: get EC2 AMI ID
    ec2_ami_facts:
      owner: amazon
      region: "{{ec2_region}}"
      filters:
        architecture: x86_64
        name: Windows_Server-2016-English-Full-Base-2018.04.11
    register: ec2_ami_details
  - set_fact: ec2_ami_id={{ec2_ami_details.images[0].image_id}}
  - debug: var=ec2_ami_id
  tags: ami,instance

- block:
  - name: get ec2 group details
    ec2_group_facts:
      region: "{{ec2_region}}"
      filters:
        group-name: "{{ec2_group_name}}"
    register: ec2_group_details

  - include_tasks: createinstance.yml vm_name={{item.key}} vm_details={{item.value}}
    with_dict: "{{vms}}"

  tags: instance
