---

# Windows Server 2016: ami-3633b149

- name: get EC2 AMI ID
  ec2_ami_facts:
    filters:
      architecture: x86_64
      is-public: true
      region: "{{ec2_region}}"
      name: Windows_Server-2016-English-Full-Base-2018.04.11
  register: ec2_ami_details

- debug: var=ec2_ami_details.images[0].image_id

# - name: create ec2 instance
#   ec2:
#     instance_type: "{{item.value.instance_type}}"
#     count: "{{item.value.count}}"
#     group: "{{ec2_group_name}}"
#     image:
#     instance_tags: "{{item.value.tags}}"
#     wait: yes
#     user_data: "{{user_data}}"
#   with_dict: "{{vms}}"
