---
# variables for ansible-roles/ec2-create-group
ec2_group_name: sharepointdev
ec2_region: us-east-1
ec2_vpc_name: sharepointvpc
ec2_vpc_block: 10.10.0.0/16
ec2_subnets:
  sp:
    cidr: 10.10.0.0/28
  db:
    cidr: 10.10.0.16/28
ec2_ports:
 - { proto: "tcp", from: "80", to: "80" }
 - { proto: "tcp", from: "22", to: "22" }
 - { proto: "tcp", from: "8080", to: "8080" }
 - { proto: "tcp", from: "5986", to: "5986" }
 - { proto: "tcp", from: "1433", to: "1433" }

vms:
  sp:
    instance_type: t2.large
    count: 1
    tags:
      Name: sharepoint
      Desc: Sharepoint Server

user_data: |
  <powershell>
  $admin = [adsi]("WinNT://./administrator, user")
  $admin.PSBase.Invoke("SetPassword", "myTempPassword123!")
  Invoke-Expression ((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))
  </powershell>
