---
# variables for ansible-roles/ec2-create-group
ec2_group_name: sharepointdev
ec2_region: us-east-1
ec2_vpc_name: sharepointvpc
ec2_vpc_block: 10.10.0.0/16
ec2_ports:
 - { proto: "tcp", from: "80", to: "80" }
 - { proto: "tcp", from: "22", to: "22" }
 - { proto: "tcp", from: "8080", to: "8080" }
 - { proto: "tcp", from: "5986", to: "5986" }
 - { proto: "tcp", from: "1433", to: "1433" }
