- name: Create AD Domain Controller
  hosts: ad

  tasks:
  - set_fact: domain_admin_username={{inventory_hostname}}\{{ansible_user}}
  - set_fact: domain_admin_username_client={{dns_name}}\{{ansible_user}}
  - win_domain:
      dns_domain_name: "{{dns_name}}"
      safe_mode_password: "{{domain_admin_password}}"
      log_path: C:\ansible_win_domain.txt
    register: domain_output

  - name: reboot if needed
    win_reboot:
    when: domain_output.reboot_required

  - win_domain_controller:
      dns_domain_name: "{{dns_name}}"
      domain_admin_user: "{{domain_admin_username}}"
      domain_admin_password: "{{domain_admin_password}}"
      safe_mode_password: "{{domain_admin_password}}"
      state: domain_controller
      log_path: c:\ansible_win_domain_controller.txt

  - name: Get existing OUs
    win_shell: Get-ADOrganizationalUnit -Identity '{{domain_ou_path}}'
    ignore_errors: yes
    register: existing_ous

  - name: Create OU
    win_shell: New-ADOrganizationalUnit -Name "{{domain_ou}}"
    when: existing_ous|failed 

  - win_domain_user:
      name: "{{item}}"
      password: "{{domain_admin_password}}"
      groups: 'Domain Admins'
      password_never_expires: true
    with_items: "{{ad_accounts}}"
